# Generated by Django 5.0.6 on 2024-05-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='products_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='products_audio/')),
                ('docx', models.FileField(blank=True, null=True, upload_to='products_files/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
